name: workout_manager
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: true
  ios: false
  image_path: "assets/magic_black.png"


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/AvenirNextLTPro-Regular.otf
        - asset: assets/fonts/Avenir/AvenirNextLTPro-It.otf
          style: italic
        - asset: assets/fonts/Avenir/AvenirNextLTPro-Bold.otf
          weight: 700
        - asset: assets/fonts/Avenir/AvenirNextLTPro-BoldCn.otf
          weight: 600
        - asset: assets/fonts/Avenir/AvenirNextLTPro-Demi.otf
          weight: 500
        - asset: assets/fonts/Avenir/AvenirNextLTPro-DemiCn.otf
          weight: 400
    - family: Futura
      fonts:
        - asset: assets/fonts/futura/Futura-CondensedLight.otf
        - asset: assets/fonts/futura/Futura_Book_Italic.ttf
          style: italic
        - asset: assets/fonts/futura/Futura_Bold.ttf
          weight: 700
        - asset: assets/fonts/futura/Futura_Heavy.ttf
          weight: 600
        - asset: assets/fonts/futura/futura_medium_bt.ttf
          weight: 500
        - asset: assets/fonts/futura/Futura_Light.ttf
          weight: 400
        - asset: assets/fonts/futura/unicode.futurab.ttf
          weight: 300
